# Generated by Django 4.2.5 on 2023-10-10 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2023, 10, 10, 6, 57, 25, 201599, tzinfo=datetime.timezone.utc))),
                ('endDate', models.DateTimeField(default=datetime.datetime(2023, 10, 10, 6, 57, 25, 201599, tzinfo=datetime.timezone.utc))),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinderKeeper.user')),
            ],
        ),
    ]
