# Generated by Django 4.2.5 on 2023-10-18 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinderKeeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDate',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 7, 31, 16, 199108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 7, 31, 16, 199108, tzinfo=datetime.timezone.utc)),
        ),
    ]
