# Generated by Django 4.2.5 on 2023-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinderKeeper', '0002_remove_event_enddate_remove_event_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
