# Generated by Django 4.2.5 on 2023-10-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinderKeeper', '0003_alter_event_endtime_alter_event_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
