# Generated by Django 4.2.5 on 2023-11-19 05:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FinderKeeper', '0005_alter_event_uid_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], max_length=5),
        ),
    ]
